import mongoose from "mongoose";

const noteSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: false, // May be generated by AI
    },
    content: {
      type: String,
      required: true, // The user's original note
    },
    summary: {
      type: String,
      default: "", // To store the AI-generated summary
    },
    elaboration: {
      type: String,
      default: "", // Added this field for the 'Elaborate' feature
    },
  },
  { timestamps: true } // Automatically adds createdAt and updatedAt
);

const Note = mongoose.model("Note", noteSchema);

export default Note;